name: example
description: "An example app for the sketchy_design_lang package showing off the design system."
publish_to: 'none'

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.12.0
  google_fonts: ^6.3.2
  intl: ^0.20.2
  sketchy_design_lang:
    path: ../

dev_dependencies:
  all_lint_rules_community: ^0.0.38
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Excalifont
      fonts:
        - asset: assets/fonts/Excalifont-Regular.ttf
    - family: XKCD
      fonts:
        - asset: assets/fonts/xkcd-Regular.otf
