name: sketchy_design_lang
description: "A new Flutter package project."
version: 0.1.0
homepage: https://github.com/csells/sketchy_design_lang
repository: https://github.com/csells/sketchy_design_lang
publish_to: "none"

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  wired_elements:
    path: third_party/wired_elements
  rough_flutter: ^0.1.2
  rough_notation: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  all_lint_rules_community: ^0.0.38
